language: python

python:
    - "3.7"

matrix:
  include:
  - os: linux
    dist: bionic

install:
    - python3 -m pip install taichi
    - python3 -m pip install requests
    - wget https://pypi.python.org/packages/53/fe/9e0fbdbca15c2c1253379c3a694f4315a420555e7874445b06edeaeacaea/coverage-4.2.tar.gz#md5=1e09362a3f35d589f942359441050a6e
    - tar zxf coverage-4.2.tar.gz
    - mv coverage-4.2/coverage tests/coverage
    - rm -rf coverage-4.2

script:
    - python3 tests/runner.py

after_success:
    bash <(curl -s https://codecov.io/bash)
